services:
  backend:
    build:
      context: ./backend
    container_name: crypto-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    env_file: 
      - ./backend/.env
    command: npm run dev
    depends_on:
      - redis
      - db

  frontend:
    build:
      context: ./frontend
    container_name: crypto-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host

  redis:
    image: redis:8.0
    container_name: crypto-redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: crypto-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
  frontend_node_modules:
  backend_node_modules:
